apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur-artifactory-api-key-token
  namespace: esphcapp
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: conjur-artifactory-cluster-store
    kind: ClusterSecretStore
  data:
  - secretKey: APP_PASSWORD
    remoteRef:
      key: it/hc_service_account/tutorial-saurapa2/app-password